### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by cisko99za** [ShahriarXD/MULTITHREAD-SPOTIFY-ACCOUNT-CHECKER-NO-PROXIES#1]
i've installed all needed but i don't find script.py....
how to ??

**Comment by ghost** [comment]
Rename main.py to script.py 
itll fix your issue .....

bigger issue is that spotify checkers are all non working... :(

**Comment by cisko99za** [comment]
i've renamed file to script.py. on same folder i've put chromedriver.exe but when run python script.py i see that:

D:\Python-3.8.1 x64>python script.py
Traceback (most recent call last):
  File "script.py", line 189, in <module>
    main = Main("combo.txt", 10)
  File "script.py", line 151, in __init__
    self.Thread  = Spotify_checker(self.combo, self.result_rep)
  File "script.py", line 24, in __init__
    self.driver = webdriver.Chrome(options = self.chrome_options)
  File "D:\Python-3.8.1 x64\App\Python\lib\site-packages\selenium\web
driver\chrome\webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "D:\000\z_tmp2\Python-3.8.1 x64\App\Python\lib\site-packages\selenium\web
driver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\000\z_tmp2\Python-3.8.1 x64\App\Python\lib\site-packages\selenium\web
driver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\Python-3.8.1 x64\App\Python\lib\site-packages\selenium\web
driver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\000\z_tmp2\Python-3.8.1 x64\App\Python\lib\site-packages\selenium\web
driver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot fi
nd Chrome binary


this error to your script or problem with spotify server ???

**Comment by ghost** [comment]
are you running this on windows ??

**Comment by cisko99za** [comment]
yes. win 7 x64 and python portable 3.81

**Comment by ghost** [comment]
Have  you tried to import the package called webdriver_manager? if not you can installed it by:

pip install webdriver_manager
Also this can be done automatically using webdriver-manager

Your system needs to know where to locate the chromedriver.exe. You could put it into a directory that is in your system's PATH variable, or just tell the constructor where it is:

Example: browser = webdriver.Chrome('C:\\path\\to\\chromedriver.exe')



https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver

**Comment by ghost** [comment]
ive never messed with portable only install with windows or the right way through linux ^-^ so what i posted may not apply to you but its the best i got

**Comment by cisko99za** [comment]
1) many tanxs for your support.... very hard this way...
2) i have put chromedriver.exe and chrome.exe into my variable path ....AppData\Local\Google\Application like info here https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver
3) i have already (and now again) install chromedriver on python with python -m pip install chromedriver like to your page suggests (and also python -m pip install selenium)
4) now when run python script.py i have on cmd widow:

  File "script.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by ghost** [comment]
to be honest im not sure on what caused that issue for you im sorry ! but please remember that almost all Spotify checkers are down ATM

**Comment by cisko99za** [comment]
down ATM? I don't understand. what do you mean?
and yes if you mean that all the checkers here are all offline you're right... but after endless searches i found a site that does an online check and that works very well, i tested it on some of my accounts and detected the fake ones from the ones that work (although free), so an updated and working method exists.

**Comment by ghost** [comment]
I wish i could make you realize that an online wbsite checker are NEVER NEVER NEVER way to go man! it logs everything your doing so if you added account it logged it if you got a hit it logged it if failed Logged!! online website checkers are not security safe..  
and with all do respect if you coded you would realize the potential danger you are facing ! so maybe itll be easier if you learn how to code it on your own.. there have been many people trying to help and explain things to you !

All your doing is making the accounts you checked public so i wouldn't cross my fingers thinking they will stay alive for long =/
 
So i wish you good luck! just be safe out there :) Sorry i couldn't have Helped MOre
